name: Gerar APK do Adla

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar o código do repositório
      uses: actions/checkout@v4

    - name: Configurar o Java (JDK)
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    
    - name: Configurar o Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: '8.7' 

    
    - name: Compilar o APK de Teste (Debug)
      run: gradle assembleDebug

    - name: Salvar e disponibilizar o APK
      uses: actions/upload-artifact@v4
      with:
        name: adla-apk-teste
        path: app/build/outputs/apk/debug/*.apk
